name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: actions/ssh-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          username: ${{ secret.SSH_USERNAME }}
          key: ${{ secret.SSH_KEY }}
          port: ${{ secret.SSH_PORT }}
          script: |
            cd ~/forum-api
            git pull origin main
            npm install
            npm run migrate up
            pm2 restart forum-api