name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ $matrix.node-version }}
        uses: actions/setup-node@v2
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          
          ACCESS_TOKEN_KEY: ${{ $secret.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ $secret.REFRESH_TOKEN_KEY }}
          TOKEN_AGE: ${{ $secret.TOKEN_AGE }}

          PGHOST: ${{ $secret.PGHOST }}
          PGPORT: ${{ $secret.PGPORT }}
          PGUSER: ${{ $secret.PGUSER }}
          PGPASSWORD: ${{ $secret.PGPASSWORD }}
          PGDATABASE: ${{ $secret.PGDATABASE }}

          PGHOST_TEST: ${{ $secret.PGHOST_TEST }}
          PGPORT_TEST: ${{ $secret.PGPORT_TEST }}
          PGUSER_TEST: ${{ $secret.PGUSER_TEST }}
          PGPASSWORD_TEST: ${{ $secret.PGPASSWORD_TEST }}
          PGDATABASE_TEST: ${{ $secret.PGDATABASE_TEST }}